name: CI-Qualidade

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar pasta src
        run: |
          if [ ! -d src ]; then
            echo "Pasta src não encontrada"
            exit 1
          fi

      - name: Verificar CSS
        run: |
          if [ ! -f src/css/style.css ]; then
            echo "CSS não encontrado no caminho correto"
            exit 1
          fi

      - name: Instalar HTMLHint
        run: npm install -g htmlhint

      - name: Rodar HTMLHint
        run: htmlhint src/index.html

      - name: Footer obrigatório
        run
